# serverless.yml
service: lambda-selenium1

package:
  artifact: build/libs/lambda-selenium.jar

provider:
  name: aws
  stage: stage
  runtime: java8
  memorySize: 3008
  timeout: 300
  versionFunctions: false

functions:
  'lambda-selenium-demo':
    handler: 'com.blackboard.testing.lambda.LambdaTestHandler::handleRequest'
    name: lambda-selenium-function1
    description: Lambda Selenium Demo Tests
